config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sulaymonqori.urls'))
]

sulaymonqori/urls.py
from django.urls import path

from sulaymonqori.views import HomeView, PostDetailView, RegisterView, PostUpdateView, PostDeleteView, PostCreateView, \
    PostListView, AboutView

app_name = "blog"
urlpatterns = [
    path('', HomeView.as_view(), name="homepage"),
    path('about/', AboutView.as_view(), name="about"),

    path('register/', RegisterView.as_view(), name='register'),
    path('post/', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post_detail"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name="post_delete"),
]

sulaymonqori/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(AbstractBaseModel):
    title = models.CharField(max_length=120)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

sulaymonqori/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from sulaymonqori.models import Post


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body"]

sulaymonqori/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, DetailView, DeleteView, UpdateView, ListView

from sulaymonqori.forms import RegistrationForm, PostCreateForm
from sulaymonqori.models import Post


class HomeView(View):
    def get(self, request):
        posts_for_homepage = Post.objects.order_by('-created_at')[:10]
        context = {
            "posts": posts_for_homepage,
        }

        return render(request, 'home.html', context=context)


class AboutView(TemplateView):
    template_name = 'about.html'


class PostDetailView(DetailView):
    template_name = "post_detail.html"
    model = Post
    context_object_name = "post"


class PostListView(ListView):
    model = Post
    template_name = 'user_posts.html'
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        return queryset


class PostCreateView(LoginRequiredMixin, CreateView):
    success_url = "blog:homepage"
    template_name = "post_create.html"
    success_message = "%(post) was published successfully"
    fields = ["title", "body"]


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ["title", "body"]
    success_url = "blog:homepage"
    template_name = "post_update.html"

    # success_message = "%(post) was updated successfully"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog:homepage")
    template_name = "post_confirm_delete.html"


class RegisterView(View):
    # template_name = 'register.html'

    def get(self, request):
        form = RegistrationForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        return render(request, 'register.html', {'form': form})

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    About us
{% endblock %}
{% block body %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>About Page</h1>
                <div class="container mt-5">
                    <h2>About Us</h2>
                    <p>Welcome to our Django Blog! This blog is dedicated to sharing knowledge, experiences, and
                        thoughts on various topics.</p>

                    <h3>Our Mission</h3>
                    <p>Our mission is to provide valuable and insightful content to our readers. We aim to engage,
                        educate, and entertain through our blog posts.</p>

                    <h3>Meet the Team</h3>
                    <p>We are a passionate team of writers, developers, and enthusiasts who love sharing our expertise
                        with the world.</p>

                    <!-- Add more content about your team, mission, etc. -->

                    <p>Feel free to explore our blog and discover a wide range of articles covering different
                        subjects.</p>
                </div>

            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
     

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>{% block title %}

    {% endblock %}</title>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog:homepage' %}">Django Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'blog:homepage' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'blog:post_create' %}">New Post</a>
                        <a class="nav-item nav-link" href="{% url 'blog:post_list' %}">Profile</a>
                        <a class="nav-item nav-link" href="#">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="login.html">Login</a>
                        <a class="nav-item nav-link" href="{% url 'blog:register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

{% block body %}

{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Home page
{% endblock %}
{% block body %}

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if posts %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            <h5>{{ message|safe }}</h5>
                        </div>
                    {% endfor %}

                {% endif %}
                <div class="alert alert-{{ message.tags }}">
                    <h5>Django messages might be shown here</h5>
                </div>
                <h3>Lastest Posts</h3>
                {% for post in posts %}
                    <article class="media content-section">
                        <img class="rounded-circle article-img" src="{% static 'img/corey.jpeg' %}" alt="">
                        <div class="media-body">
                            <div class="article-metadata">
                                <a class="mr-2" href="user_posts.html">{{ post.author.username }}</a>
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                            <h5><a class="article-title"
                                   href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h5>
                        </div>
                    </article>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>


{% endblock %}

templates/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Delete Post
{% endblock %}
{% block body %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if posts %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            <h5>{{ message|safe }}</h5>
                        </div>
                    {% endfor %}

                {% endif %}
                <div class="content-section">
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Delete Post</legend>
                            <h2>Are you sure you want to delete the post {{ post.title }}</h2>
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                            <a class="btn btn-outline-secondary" href="{% url 'blog:post_detail' post.id %}">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

          

templates/post_create.html
{% extends 'base.html' %}
{% load sttaic %}
{% block title %}
	Add New Post
{% endblock %}
{% block body %}
	<main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
              <div class="alert alert-{{ message.tags }}">
                <h3>Django messages might be shown here</h3>
              </div>
                    <div class="content-section">
                        <form >
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Blog Post</legend>
                                <div class="form-group">
                                    <label for="title">Title</label>
                                    <input type="text" class="form-control" id="title" name="title" placeholder="Enter the title">
                                </div>
                                
                                <div class="form-group">
                                    <label for="content">Content</label>
                                    <textarea class="form-control" id="content" name="content" rows="4" placeholder="Enter the content"></textarea>
                                </div>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-info" type="submit">Post</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-4">
                  <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                      </ul>
                    </p>
                  </div>
                </div>
              </div>
            </main>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Post details
{% endblock %}
{% block body %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
{#                <div class="alert alert-{{ message.tags }}">#}
{#                    <h3>Django messages might be shown here</h3>#}
{#                </div>#}
                <article class="media content-section">
                    <img class="rounded-circle article-img" src="corey.jpeg">
                    <div class="media-body">
                        <div class="article-metadata">
                            <a class="mr-2" href="user_posts.html">{{ post.title }}</a>
                            <small class="text-muted">{{ post.created_at }}</small>
                            <div>
                                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="#">Update</a>
                                <a class="btn btn-danger btn-sm mt-1 mb-1" href="post_confirm_delete.html">Delete</a>
                            </div>

                        </div>
                        <h2 class="article-title">{{ post.title }}</h2>
                        <p class="article-content">{{ post.body }}
                        </p>
                    </div>
                </article>
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/post_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Update post
{% endblock %}
{% block body %}
    <main role="main" class="container">
        <h2>Update post</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </main>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block title %}
	Register
{% endblock %}
{% block content %}
    <main role="main" class="container">
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
    </main>
{% endblock %}

templates/user_posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    User's Posts
{% endblock %}
{% block body %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if posts %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            <h5>{{ message|safe }}</h5>
                        </div>
                    {% endfor %}

                {% endif %}
                <h1 class="mb-3">Posts by Andrew Ng </h1>

                {% for post in posts %}
                <article class="media content-section">
                    <img class="rounded-circle article-img" src="andrew.jpeg">
                    <div class="media-body">
                        <div class="article-metadata">
                            <a class="mr-2" href="{% url 'blog:post_list' %}">{{ post.author.username }}</a>
                            <small class="text-muted">{{ post.created_at }}</small>
                        </div>
                        <h4><a class="article-title" href="post_detail.html">{{ post.title }}</a></h4>
                        <p class="article-content">{{ post.body|slice:100 }}</p>
                    </div>
                </article>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
    